### ISSUE TITLE
As a user i should be able to update my profile

### ISSUE THREAD

**Issue by KA-devl** [KA-devl/VueLovers-soen341project2023#22]

**Comment by Sanassah** [comment]
Assessed at the beginning of SPRINT2

Difficulty:
3

Priority:
HIGH - Required to edit profile information and taking advantage of the main functions of the app.

Risk:
HIGH - Essential for each individual to have his own information on the site and be able to edit it

**Comment by Sanassah** [comment]
![image](https://user-images.githubusercontent.com/89364990/222763232-8f5b9610-7cd9-47bc-9ad7-9ccb2bb59b3c.png)
