### ISSUE TITLE
As a user i should be able to create an account (Employee vs Employer)

### ISSUE THREAD

**Issue by KA-devl** [KA-devl/VueLovers-soen341project2023#23]

**Comment by Sanassah** [comment]
Assessed at the beginning of SPRINT2

Difficulty:
3

Priority:
HIGH - Required for initializing of a profile and taking advantage of the main functions of the app.

Risk:
HIGH - Essential for each individual to have his own information on the site

**Comment by Sanassah** [comment]
![image](https://user-images.githubusercontent.com/89364990/222758760-1c3610e7-45e7-4bb4-9bcf-4df28e7e5258.png)
