### ISSUE TITLE
1) As a candiate I should be able to put my information in a profile for the employer to see

### ISSUE THREAD

**Issue by Sanassah** [KA-devl/VueLovers-soen341project2023#43]

**Comment by Sanassah** [comment]
Difficulty:
4

Priority:
HIGH - Required for initializing of a profile and taking advantage of the main function of the app.

Risk:
HIGH - Essential for employers to see candidates profile description and compare applications

**Comment by npiperni** [comment]
![image](https://user-images.githubusercontent.com/36056036/227663915-72643be4-6222-4a4b-9aaf-54602b8b368e.png)
