### ISSUE TITLE
5) The user shall be able to delete and upload his resume for the employer to see

### ISSUE THREAD

**Issue by Sanassah** [KA-devl/VueLovers-soen341project2023#63]
Assessed at the beginning of SPRINT3

Associated Tasks:
-Font end design
-Datbase setup to store the resume
-Create endpoint for the resume 

Difficulty:
3

Priority:
HIGH - Required for the candidate to show his experiences to the employer

Risk:
HIGH - Essential for each individual to be able to delete his resume and upload another one for the employer to be updated

**Comment by npiperni** [comment]
![image](https://user-images.githubusercontent.com/36056036/227661198-30c9d673-255a-48a5-8d01-5a181133a6b7.png)

**Comment by Sanassah** [comment]
Done
